### ISSUE TITLE
request-output for display

### ISSUE THREAD

**Issue by montyfert** [techman83/Octoprint-Filament-Scale#42]
hi sorry to be a pain but is there a way to add asimple display to the pi gpio's to display the weight in real time. 
eg - TM1637 or a SH1106, SSD1306
thanks 
martin
keep up the good work much apreciated

**Comment by techman83** [comment]
@montyfert - that's well outside the scope of this library. If there is a plugin that provides a simple interface like the mqtt one, possibly if someone wants to write it.

What you were attempting with Tasmota is probably doable, but there is a pretty steep learning curve. Berry is useful, but you would want to start with understanding how some of the examples work before writing something custom.

**Comment by montyfert** [comment]
thanks 
martin
